server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB HOST:localhost}:3306/phoneshop
    username: root
    password: password123
    driverClassName: com.mysql.jdbc.Driver
  jpa :
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PHONESHOP